all: compile

compile: MemberNode.java CentralCommunicationController.java
	javac MemberNode.java
	javac CentralCommunicationController.java

clean:
	rm -f MemberNode.class
	rm -f CentralCommunicationController.class